// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.34209
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Olifant.JiraMetrics.Test.Acceptance.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("JM1 - Present project progress")]
    [NUnit.Framework.CategoryAttribute("web")]
    public partial class JM1_PresentProjectProgressFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "JM1 - Present project progress.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "JM1 - Present project progress", "In order to get a grip on project risks \r\nAs a stakeholder\r\nI want to see the pro" +
                    "ject progress in a burn-up \r\nand the graph should be updated daily", ProgrammingLanguage.CSharp, new string[] {
                        "web"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("1 - View burn-up")]
        [NUnit.Framework.CategoryAttribute("no_data_changes")]
        public virtual void _1_ViewBurn_Up()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("1 - View burn-up", new string[] {
                        "no_data_changes"});
#line 10
this.ScenarioSetup(scenarioInfo);
#line 11
 testRunner.When("I navigate to \"burn-up\" page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 12
 testRunner.And("I wait, but not longer than 1 second", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
 testRunner.Then("I should see a burn-up graph", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Project name"});
            table1.AddRow(new string[] {
                        "OFU"});
            table1.AddRow(new string[] {
                        "Disco"});
            table1.AddRow(new string[] {
                        "SCSC"});
#line 14
 testRunner.And("I should see a dropdown with selectable projects:", ((string)(null)), table1, "And ");
#line 19
 testRunner.But("the statuses should be hidden", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "But ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("2 - Plot issues from query in burn-up")]
        [NUnit.Framework.CategoryAttribute("no_data_changes")]
        public virtual void _2_PlotIssuesFromQueryInBurn_Up()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("2 - Plot issues from query in burn-up", new string[] {
                        "no_data_changes"});
#line 23
this.ScenarioSetup(scenarioInfo);
#line 24
 testRunner.Given("I navigate to \"burn-up\" page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 25
 testRunner.When("I query \"Disco\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 26
 testRunner.Then("I should see a burn-up graph", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Start X",
                        "Y values"});
            table2.AddRow(new string[] {
                        "start",
                        "0, 1"});
#line 27
 testRunner.And("I should see the following values in the graph:", ((string)(null)), table2, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("3 - Load JiraMetrics with new issues from Jira")]
        public virtual void _3_LoadJiraMetricsWithNewIssuesFromJira()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("3 - Load JiraMetrics with new issues from Jira", ((string[])(null)));
#line 31
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Key",
                        "Story points"});
            table3.AddRow(new string[] {
                        "DISCO-665",
                        "7"});
            table3.AddRow(new string[] {
                        "OFU-1462",
                        "4"});
#line 32
 testRunner.Given("JiraMetrics contains the following issues:", ((string)(null)), table3, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Project",
                        "Key",
                        "Story Points"});
            table4.AddRow(new string[] {
                        "DISCO",
                        "DISCO-937",
                        "1"});
            table4.AddRow(new string[] {
                        "DISCO",
                        "DISCO-846",
                        "5"});
            table4.AddRow(new string[] {
                        "OFU",
                        "OFU-2290",
                        "6"});
#line 36
 testRunner.And("Jira contains additional issues:", ((string)(null)), table4, "And ");
#line 41
 testRunner.When("I navigate to \"admin\" page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 42
 testRunner.And("I load JiraMetrics with issues from Jira project \"Disco\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 43
 testRunner.And("I wait, but not longer than 5 seconds", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "issue",
                        "action"});
            table5.AddRow(new string[] {
                        "DISCO-937",
                        "Added"});
            table5.AddRow(new string[] {
                        "DISCO-846",
                        "Added"});
#line 44
 testRunner.Then("I should be presented a list of all issues that has been added:", ((string)(null)), table5, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("4 - Updating graph with new issues")]
        public virtual void _4_UpdatingGraphWithNewIssues()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("4 - Updating graph with new issues", ((string[])(null)));
#line 50
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Key",
                        "Story points"});
            table6.AddRow(new string[] {
                        "DISCO-665",
                        "1"});
            table6.AddRow(new string[] {
                        "OFU-1462",
                        "4"});
#line 51
 testRunner.Given("JiraMetrics contains the following issues:", ((string)(null)), table6, "Given ");
#line 55
 testRunner.When("I navigate to \"admin\" page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Project",
                        "Key",
                        "Story Points",
                        "Status"});
            table7.AddRow(new string[] {
                        "DISCO",
                        "DISCO-620",
                        "7",
                        "Resolved"});
#line 56
 testRunner.And("I load JiraMetrics with project \"Disco\" having the following issue:", ((string)(null)), table7, "And ");
#line 59
 testRunner.And("I navigate to \"burn-up\" page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 60
 testRunner.And("I query \"Disco\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 61
 testRunner.And("I wait, but not longer than 10 second", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Start X",
                        "End X",
                        "Y values"});
            table8.AddRow(new string[] {
                        "start",
                        "y14w51",
                        "0, 1, 3.5, 10.5, 12.0, 13.0"});
#line 62
 testRunner.Then("I should see the following values in the graph:", ((string)(null)), table8, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("5 - Load JiraMetrics with changed issues from Jira")]
        [NUnit.Framework.CategoryAttribute("wip")]
        public virtual void _5_LoadJiraMetricsWithChangedIssuesFromJira()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5 - Load JiraMetrics with changed issues from Jira", new string[] {
                        "wip"});
#line 68
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Key",
                        "Story points"});
            table9.AddRow(new string[] {
                        "DISCO-665",
                        "1"});
#line 69
 testRunner.Given("JiraMetrics contain the following issue:", ((string)(null)), table9, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Project",
                        "Key",
                        "Story Points"});
            table10.AddRow(new string[] {
                        "DISCO",
                        "DISCO-665",
                        "40"});
#line 72
 testRunner.And("Jira contains updated issues from \'2015-05-15\':", ((string)(null)), table10, "And ");
#line 75
 testRunner.When("I navigate to \"admin\" page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 76
 testRunner.And("I load JiraMetrics with issues from Jira project \"Disco\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 77
 testRunner.And("I wait, but not longer than 5 seconds", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "issue",
                        "action"});
            table11.AddRow(new string[] {
                        "DISCO-665",
                        "Updated"});
#line 78
 testRunner.Then("I should be presented a list of all issues that has been updated:", ((string)(null)), table11, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("6 - Updating graph with changed issues")]
        public virtual void _6_UpdatingGraphWithChangedIssues()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("6 - Updating graph with changed issues", ((string[])(null)));
#line 83
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "project",
                        "issue",
                        "status",
                        "Story Points"});
            table12.AddRow(new string[] {
                        "Disco",
                        "DISCO-1462",
                        "Closed",
                        "3"});
            table12.AddRow(new string[] {
                        "Disco",
                        "DISCO-2299",
                        "Implementing",
                        "4"});
            table12.AddRow(new string[] {
                        "OFU",
                        "OFU-676",
                        "Closed",
                        "5"});
#line 84
 testRunner.Given("the system contains the following issues:", ((string)(null)), table12, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Start X",
                        "End X",
                        "Start Y",
                        "End Y"});
            table13.AddRow(new string[] {
                        "start",
                        "y14w51",
                        "0",
                        "3"});
#line 89
 testRunner.And("I choose project \"Disco\" to get the following values in the burn-up graph:", ((string)(null)), table13, "And ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "project",
                        "issue",
                        "status"});
            table14.AddRow(new string[] {
                        "Disco",
                        "DISCO-2299",
                        "Closed"});
#line 92
 testRunner.When("the following issue is updated to the system from Jira:", ((string)(null)), table14, "When ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "Start X",
                        "End X",
                        "Start Y",
                        "End Y"});
            table15.AddRow(new string[] {
                        "start",
                        "y14w51",
                        "0",
                        "7.0"});
#line 95
 testRunner.Then("I should be able to see the following values in the burn-up graph:", ((string)(null)), table15, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("7 - Loading JiraMetrics when no new issues needs to be loaded")]
        [NUnit.Framework.CategoryAttribute("no_data_changes")]
        public virtual void _7_LoadingJiraMetricsWhenNoNewIssuesNeedsToBeLoaded()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("7 - Loading JiraMetrics when no new issues needs to be loaded", new string[] {
                        "no_data_changes"});
#line 101
this.ScenarioSetup(scenarioInfo);
#line 102
 testRunner.Given("JiraMetrics contains all the latest versions of issues in Jira", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 103
 testRunner.When("I navigate to \"admin\" page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 104
 testRunner.And("I load JiraMetrics with issues from Jira project \"Disco\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 105
 testRunner.And("I wait, but not longer than 5 second", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 106
 testRunner.Then("I should be presented a message \"All issues are up-to-date for project Disco\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
